version: "3.9"
    
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DBNAME: obbs
      MYSQL_PASSWORD: root
    container_name: mysql
    networks:
      - obbsweb

  # phpmyadmin

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    ports: 
     - '8081:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
      - PMA_ARBITRARY=1 
    links:
     - db
    networks:
      - obbsweb
    volumes:
      - /sessions
    container_name: obbs-phpmyadmin

  # Webserver

  webserver:
    depends_on:
      - db
    image: praful2018/obbsweb:v1
    volumes:
      - phpweb_data:/var/www/html
    ports:
      - "8082:80"
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DBNAME: obbs
    networks:
      - obbsweb  
networks:
    obbsweb:
  
  
volumes:
  db_data: {}
  phpweb_data: {}